name: Export Godot 4 Game

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: firebelley/setup-godot@v2
        with:
          version: "4.2.2"
          include-templates: true
          use-dotnet: false

      - name: Export Windows
        run: godot --headless --export-release "Windows Desktop" build/game.exe

      - name: Export Linux
        run: godot --headless --export-release "Linux/X11" build/game.x86_64

      - name: Export macOS
        run: godot --headless --export-release "macOS" build/game.app.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Godot-Builds
          path: build/
